CC = gcc
CFLAGS = -Wall -g -O2

TARGET := 16_mysed
SRCS := 16_mysed.c
OBJS := $(SRCS:.c=.o)

all: $(TARGET)

$(TARGET): $(SRCS)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRCS)

clean:
	rm -f $(TARGET) $(OBJS)

.PHONY: all clean